# Generated by Django 4.2.2 on 2023-10-02 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketstable',
            options={'ordering': ['-price']},
        ),
    ]
