# List of proxy servers
proxies:
  - name: JP1
    user: 2WknpZuD
    pass: GgEBBEGs
    url: http://213.209.139.114:63758

  - name: JP2
    user: 2WknpZuD
    pass: GgEBBEGs
    url: http://82.117.93.18:62828

  - name: JP3
    user: 2WknpZuD
    pass: GgEBBEGs
    url: http://45.83.86.40:64562

  - name: JP4
    user: 2WknpZuD
    pass: GgEBBEGs
    url: http://92.240.216.237:63906

  - name: JP5
    user: 2WknpZuD
    pass: GgEBBEGs
    url: http://103.165.76.86:63448



# List of tickets for parsing by exchanges
tickets:
  - - USDT # coin
    - USD # fiat
    - BUY # type trade


  - - USDT
    - USD
    - SELL

  - - USDT
    - EUR
    - BUY

  - - USDT
    - EUR
    - SELL

  - - BTC
    - USD
    - BUY

  - - BTC
    - USD
    - SELL

  - - BTC
    - EUR
    - BUY

  - - BTC
    - EUR
    - SELL

  - - USDC
    - USD
    - BUY

  - - USDC
    - USD
    - SELL

  - - USDC
    - EUR
    - BUY

  - - USDC
    - EUR
    - SELL

  - - ETH
    - USD
    - BUY

  - - ETH
    - USD
    - SELL

  - - ETH
    - EUR
    - BUY

  - - ETH
    - EUR
    - SELL

# Pause between parsing rounds | normal:(35, 40)
delay:
  - 38 # lower
  - 41 # upper

# Limit of connections to the exchange per unit of time | normal:(25, 29)
limit:
  - 24 # lower
  - 29 # upper

# Page (request) limit for one thread | normal:(150 - 160)
limit_requests: 150

# Limit of accesses to the exchange in one thread | normal:(4 - 5)
limit_exchange: 4

# Parity of the circle at which to reload the threads.data | normal:(20)
lap_of_reload: 20

# Number of pages if the limit is exceeded
page_limit: 100

# Mode
DEBUG: False
